---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_7a573925eb94
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/honjaya
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: JWT_SECRET
            - name: REDIS_HOST
              value: redis
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: CLIENT_SECRET
            - name: REDIRECT_URI
              value: https://k2b3bc621690aa.user-app.krampoline.com/api/login/oauth2/code/kakao
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: S3_SECRET_KEY
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: honjaya-secret
                  key: ADMIN_KEY
            - name: SERVER_URL
              value: https://k2b3bc621690aa.user-app.krampoline.com
            - name: SUCCESS_URL
              value: https://k2b3bc621690aa.user-app.krampoline.com
            - name: 
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080