namespace: default
resources:
  - nginx.yml
  - mariadb.yml
  - backend.yml
  - frontend.yml
  - redis.yml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  # - name: init-db
  #   files:
  #     - configs/init.sql